apiVersion: v1
kind: Pod
metadata:
  name: php-pesbuk-secret
  labels:
    app: pesbuk-secret
spec:
  volumes:
    - name: config-secret
      configMap:
        name: p-fb-configmap-secret

  containers:
  - name: php-sosmed
    image: sekolahdevopscilsy/php-sosmed
    ports:
    - containerPort: 80
    volumeMounts:
    - name: config-secret
      mountPath: "/var/www/html/config.php"
      subPath: "config.php"
    env:
    - name: DB_HOST
      value: "php-pesbuk-secret"
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: p-secret-fb
          key: DB_USER
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: p-secret-fb
          key: DB_PASS

  - name: mysql-sosmed
    image: sekolahdevopscilsy/mysql-sosmed
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: p-secret-fb
          key: MYSQL_ROOT_PASSWORD