apiVersion: v1
kind: Secret
metadata:
  name: p-secret-fb
  namespace: devops-ramses
  labels:
    app: pesbuk-secret
type: Opaque
data:
  DB_USER: ZGV2b3BzY2lsc3k=
  DB_PASS: MTIzNDU2Nzg5MA==
  MYSQL_ROOT_PASSWORD: MTIzNDU2Nzg5MA==
